cpumem.nLoops.thousands:
 - 25000
# - 50000
# - 10000000
cpumem.nCpus:
 #- 4
 - 8
cpumem.mem.mb:
 - 128
# - 1024
cpumem.nRecords.thousands:
  - 1000
#  - 100
#  - 1000
#  - 10000
#  - 100000
#cpumem.nRecords.thousands: 100000
cpumem.nPartitions:
  - 32
